---
# run locally here, yadda yadda yadda
- hosts: vm
  become: yes
  gather_facts: false
  roles:
    - init
    - sudo
    - java
    - maven
    - gradle
    - git
    - docker
    - postgres
    - nginx
    - tomcat
    - eclipse
