---
- hosts: vm
  become: yes
  remote_user: "{{user_name}}"
  gather_facts: false
  roles:
    - init
    - sudo
    - java
    - maven
    - gradle
    - git
    - docker
    - postgres
    - nginx
    - tomcat
    - eclipse
