---
# run locally here, yadda yadda yadda
- hosts: local
  become: yes
  gather_facts: false
  roles:
    #- init
    #- sudo
    #- java
    #- maven
    #- gradle
    #- git
    #- docker
    #- postgres
    #- nginx
    #- tomcat
     - eclipse
