---
- name: add repo for java 10
  apt_repository: 
    repo='ppa:linuxuprising/java' 
    state=present

- name: set licence selected
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 select true | /usr/bin/debconf-set-selections
  sudo: yes

- name: set licence seen
  shell: /bin/echo debconf shared/accepted-oracle-license-v1-1 seen true | /usr/bin/debconf-set-selections
  sudo: yes

- name: install java 10
  apt: 
    name=oracle-java10-installer
    state=latest 
    update-cache=yes 
    force=yes
  sudo: yes

- name: Set Java 10 default
  apt: 
    name=oracle-java10-set-default
    state=latest 
    update-cache=yes 
  sudo: yes

#- name: Download Gradle {{gradle_version}} from https://services.gradle.org/distributions/{{gradle_zipfile}} to {{ ansible_cache_dir }}
# shell: "wget -4 -P {{ ansible_cache_dir }}   https://services.gradle.org/distributions/{{gradle_zipfile}}"

- name: Download Gradle {{gradle_version}} from https://services.gradle.org/distributions/{{gradle_zipfile}} to {{ ansible_cache_dir }}
  get_url: dest="{{ ansible_cache_dir }}" url=https://services.gradle.org/distributions/{{gradle_zipfile}}
  sudo: yes
  tags: [gradle]

- name: Extract Gradle
  shell: unzip "{{ ansible_cache_dir }}/{{gradle_zipfile}}" -d /usr/local/share/ creates=/usr/local/share/{{gradle_folder}}
  sudo: yes
  tags: [gradle]

- name: Add Gradle executable symlink to path
  shell: ln -s /usr/local/share/{{gradle_folder}}/bin/gradle /usr/local/bin/gradle creates=/usr/local/bin/gradle
  sudo: yes
  tags: [gradle]
