---

- name: Include OS-specific variables (RedHat).
  include_vars: "{{ ansible_os_family }}.yml"
  when:
    - ansible_os_family == "RedHat"
    - ansible_distribution != "Fedora"

- name: Include OS-specific variables (Fedora).
  include_vars: "{{ ansible_distribution }}.yml"
  when: ansible_distribution == "Fedora"

- name: Include OS-specific variables (Debian).
  include_vars: "{{ ansible_os_family }}.yml"
  when: ansible_os_family == "Debian"

- name: Define git_install_from_source_dependencies.
  set_fact:
    git_install_from_source_dependencies: "{{ __git_install_from_source_dependencies | list }}"
  when: git_install_from_source_dependencies is not defined

- name: Ensure git's dependencies are installed (RedHat).
  package: "name={{ item }} state=present"
  with_items: "{{ git_install_from_source_dependencies }}"
  when: ansible_os_family == 'RedHat'

- name: Ensure git's dependencies are installed (Debian).
  apt: "name={{ item }} state=present"
  with_items: "{{ git_install_from_source_dependencies }}"
  when: ansible_os_family == 'Debian'

- name: Get installed version.
  command: >
    git --version
    warn=no
  changed_when: false
  failed_when: false
  check_mode: no
  register: git_installed_version

- name: Force git install if the version numbers do not match. git_install_from_source_force_update must be true in defaults/main.yml
  set_fact:
    git_reinstall_from_source: true
  when:
    - git_install_from_source_force_update
    - (git_installed_version.rc == 0) and (git_installed_version.stdout | regex_replace("^.*?([0-9\.]+)$", "\\1") is version_compare(git_version, operator="!="))

- name: Download git.
  get_url:
    url: "https://www.kernel.org/pub/software/scm/git/git-{{ git_version }}.tar.gz"
    dest: "{{ ansible_cache_dir }}/git-{{ git_version }}.tar.gz"
  when: (git_installed_version.rc != 0) or git_reinstall_from_source

- name: Expand git archive.
  unarchive:
    src: "{{ ansible_cache_dir }}/git-{{ git_version }}.tar.gz"
    dest: "{{ ansible_cache_dir }}"
    creates: "{{ ansible_cache_dir }}/git-{{ git_version }}/README"
    copy: no
  when: (git_installed_version.rc != 0) or git_reinstall_from_source

- name: Build git.
  command: >
    make prefix={{ install_directory }}/{{ git_extract_dir }} {{ item }}
    chdir={{ ansible_cache_dir }}/git-{{ git_version }}
  with_items:
    - all
    - install
  when: (git_installed_version.rc != 0) or git_reinstall_from_source
  become: yes

- name: "Add git  {{ git_version }} symlink to path"
  file:
    src: "{{ install_directory }}/{{ git_extract_dir }}/bin/git"
    dest: "{{ git_link }}"
    owner: root
    group: root
    state: link
  when: (git_installed_version.rc != 0) or git_reinstall_from_source
  become: yes

- name: "Validate Git  {{ git_version }} version"
  shell: "{{ git_link }} --version | grep {{ git_version }}"
  register: git_ver
  when: (git_installed_version.rc != 0) or git_reinstall_from_source
  become: yes

- fail:
    msg: "Seems to be git {{ git_version }} is missing ... aborting"
  when: git_ver.skipped != true and git_ver.rc != 0 and ((git_installed_version.rc != 0) or git_reinstall_from_source)
  become: yes

- name: "Validate Git  {{ git_version }} version"
  shell: "{{ git_link }} --version | grep {{ git_version }}"
  changed_when: False
  register: git_ver
  when: (git_installed_version.rc != 0) or git_reinstall_from_source
  become: yes

- debug:
    msg: "Git {{ git_version }} is installed"
  when: git_ver.skipped != true and git_ver.rc == 0 and ((git_installed_version.rc != 0) or git_reinstall_from_source)
  become: yes
